// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/Animation.vue')['default']
    Animation0: typeof import('./src/components/Animation0.vue')['default']
    Assets: typeof import('./src/components/Assets.vue')['default']
    ConnectWallet: typeof import('./src/components/ConnectWallet.vue')['default']
    CreateOrderModal: typeof import('./src/components/CreateOrderModal.vue')['default']
    Deposit: typeof import('./src/components/modal/Deposit.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    'Hero copy': typeof import('./src/components/Hero copy.vue')['default']
    MarketHistory: typeof import('./src/components/MarketHistory.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    OrderBook: typeof import('./src/components/OrderBook.vue')['default']
    RangeSlider: typeof import('./src/components/RangeSlider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TradeBar: typeof import('./src/components/TradeBar.vue')['default']
    TradeFooter: typeof import('./src/components/footer/TradeFooter.vue')['default']
    TradingView: typeof import('./src/components/TradingView.vue')['default']
    UserTrade: typeof import('./src/components/UserTrade.vue')['default']
    Volume: typeof import('./src/components/Volume.vue')['default']
    WalletModal: typeof import('./src/components/WalletModal.vue')['default']
    Withdraw: typeof import('./src/components/modal/Withdraw.vue')['default']
    WithdrawDropdown: typeof import('./src/components/modal/WithdrawDropdown.vue')['default']
  }
}
